const actionType = {
  PROCESSING_START: 'PROCESSING_START',
  PROCESSING_ERROR: 'PROCESSING_ERROR',
  SET_SELECTED_MOVIE: 'SET_SELECTED_MOVIE',
  SET_MOVIES: 'SET_MOVIES',
  ADD_MOVIE: 'ADD_MOVIE',
  UPDATE_MOVIE: 'UPDATE_MOVIE',
  DELETE_MOVIE: 'DELETE_MOVIE',
  GET_MOVIE_BY_ID: 'GET_MOVIE_BY_ID'
}

export default actionType;
