const actionType = {
  PROCESSING_START: 'PROCESSING_START',
  PROCESSING_ERROR: 'PROCESSING_ERROR',
  SET_MOVIES: 'SET_MOVIES',
  SET_FILTER: 'SET_FILTER',
  SET_SORT: 'SET_SORT',
  SET_SORT_ORDER: 'SET_SORT_ORDER'
}

export default actionType;
